<?php

/**
 * The admin-specific functionality of the plugin.
 *
 * @link       https://www.flizpay.de
 * @since      1.0.0
 *
 * @package    Flizpay
 * @subpackage Flizpay/admin
 */

/**
 * The admin-specific functionality of the plugin.
 *
 * Defines the plugin name, version, and two examples hooks for how to
 * enqueue the admin-specific stylesheet and JavaScript.
 *
 * @package    Flizpay
 * @subpackage Flizpay/admin
 * @author     Flizpay <roberto.ammirata@flizpay.de>
 */
class Flizpay_Admin
{

	/**
	 * The ID of this plugin.
	 *
	 * @since    1.0.0
	 * @access   private
	 * @var      string    $plugin_name    The ID of this plugin.
	 */
	private $plugin_name;

	/**
	 * The version of this plugin.
	 *
	 * @since    1.0.0
	 * @access   private
	 * @var      string    $version    The current version of this plugin.
	 */
	private $version;

	/**
	 * Initialize the class and set its properties.
	 *
	 * @since    1.0.0
	 * @param      string    $plugin_name       The name of this plugin.
	 * @param      string    $version    The version of this plugin.
	 */
	public function __construct($plugin_name, $version)
	{

		$this->plugin_name = $plugin_name;
		$this->version = $version;

	}

	/**
	 * Register the stylesheets for the admin area.
	 *
	 * @since    1.0.0
	 */
	public function enqueue_styles()
	{

		/**
		 * This function is provided for demonstration purposes only.
		 *
		 * An instance of this class should be passed to the run() function
		 * defined in Flizpay_Loader as all of the hooks are defined
		 * in that particular class.
		 *
		 * The Flizpay_Loader will then create the relationship
		 * between the defined hooks and the functions defined in this
		 * class.
		 */

		wp_enqueue_style($this->plugin_name, plugin_dir_url(__FILE__) . 'css/flizpay-admin.css', array(), $this->version, 'all');

	}

	/**
	 * Register the JavaScript for the admin area.
	 *
	 * @since    1.0.0
	 */
	public function enqueue_scripts()
	{

		/**
		 * This function is provided for demonstration purposes only.
		 *
		 * An instance of this class should be passed to the run() function
		 * defined in Flizpay_Loader as all of the hooks are defined
		 * in that particular class.
		 *
		 * The Flizpay_Loader will then create the relationship
		 * between the defined hooks and the functions defined in this
		 * class.
		 */

		wp_enqueue_script($this->plugin_name, plugin_dir_url(__FILE__) . 'js/flizpay-admin.js', array('jquery'), $this->version, false);
		wp_localize_script($this->plugin_name, 'flizpayParams', array('nonce' => wp_create_nonce('test_connection_nonce')));

	}

	/**
	 * @param $links
	 * @return array|string[]
	 */
	public function flizpay_plugin_links($links)
	{
		$plugin_links = array(
			'<a href="' . admin_url('admin.php?page=wc-settings&tab=checkout&section=flizpay') . '">' . __('Settings', 'flizpay-gateway') . '</a>',
			'<a href="https://www.docs.flizpay.de/docs/intro/">' . __('Docs', 'flizpay-gateway') . '</a>'
		);

		return array_merge($plugin_links, $links);
	}

	/**
	 * @return array
	 */
	public function load_form_fields()
	{
		return array(
			'description_banner' => array(
				'title' => __('', 'flizpay'), // Empty title, used for HTML output
				'type' => 'title', // Using 'title' as a workaround to insert HTML
				'description' => $this->add_description_banner(), // Including HTML content via a method
			),
			'flizpay_enabled' => array(
				'title' => 'Enable/Disable',
				'label' => 'Enable Flizpay Gateway',
				'type' => 'checkbox',
				'description' => '',
				'default' => 'no',
			),
			'title' => array(
				'title' => 'Title',
				'type' => 'text',
				'description' => 'This controls the title which the user sees during checkout.',
				'default' => 'FLIZpay',
				'desc_tip' => true,
			),
			'description' => array(
				'title' => 'Description',
				'type' => 'textarea',
				'description' => 'This controls the description which the user sees during checkout.',
				'default' => 'Pay securely with your bank account via the FLIZ app.',
				'desc_tip' => true,
			),
			'flizpay_api_key' => array(
				'title' => 'API KEY',
				'label' => 'Enter API KEY',
				'type' => 'text',
				'description' => 'Enter you API KEY. This information is very sensitive, it should be treated as a password.',
				'desc_tip' => false,
			),
			'flizpay_webhook_url' => array(
				'title' => 'Autogenerated URL',
				'type' => 'text',
				'description' => 'This is your custom URL that we generate when the connection succeeds.',
				'default' => '',
				'desc_tip' => true,
			),
			'flizpay_webhook_alive' => array(
				'title' => '',
				'type' => 'checkbox',
				'description' => 'This indicates when our servers manage to communicate with your site via the webhook URL. Reload the page a few seconds after testing the connection.',
				'default' => 'no',
				'desc_tip' => false,
			),
		);
	}

	private function add_description_banner()
	{
		return <<<HTML
			<h2>Flizpay</h2>
			<div style="background-color: #f7f7f7; margin-bottom: 20px; padding: 20px; border-left: 4px solid #007cba;">
				<div style="width: 100%; display: flex; justify-content: center; flex-wrap: wrap; text-align: center;">
					<h2 style="width: 100%; text-align: center;">Welcome to the FLIZpay WooCommerce plugin!</h2>
				</div>
				<p>Instructions:</p>
				<ol>
					<li>If you haven’t signed up for a FLIZ company account, please <a href="https://www.flizpay.de/signup" target="_blank">click here</a> and sign up.</li>
					<li>Once you signed up, please generate a new API Key in your FLIZ company account and paste it in the “API KEY” field below.</li>
					<li>Click to configure the connection</li>
					<li>Wait about 10 seconds and reload the page to check the connection status.</li>
					<li>After you reloaded this page, a green box is shown at the bottom, indicating the successful configuration of the FLIZpay plugin. You are now ready to receive fee-free payments.</li>
					<li>Click on “Save changes” on the bottom left.</li>
					<li>Make sure you save as many fees as possible with our fee-free payments. So, don’t forget to put FLIZpay first in the list of payment methods presented to customers. To do so, click on “Payments” at the top of this page. There, you can drag and drop or use the arrows to fix the position of a payment method in the list of available methods.</li>
				</ol>
				
				<p>If you'd like to know more about how to configure this plugin for your needs, <a
						href="https://www.docs.flizpay.de/docs/intro" target="_blank">check out
						our documentation.</a></p>
			</div>
		HTML;
	}
}
